name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Prepare some dummy drug/gene metadata (instead of loading very large files)
      run: |
        sh prepareDataForTesting.sh
    - name: Run the Snakemake pipeline on a test document
      run: |
        MODE=test snakemake --cores 1
    - name: Check that the output files have more than the header
      run: |
        test $(cat test_working/pgxmine_collated.tsv | wc -l) -gt 1
        test $(cat test_working/pgxmine_sentences.tsv | wc -l) -gt 1000
        test $(cat test_working/pgxmine_unfiltered.tsv | wc -l) -gt 1

